### ISSUE TITLE
Eliminating all BIOS dependencies and reentrant kernel issues

### ISSUE THREAD

**Issue by ghaerr** [Mellvik/TLVC#18]
Hello @Mellvik,

I just happened to run across your project... you have been very busy!! And very nice job, in particular with getting both the FD and HD direct drivers running, along with a fully interrupt-driven I/O subsystem :) Your research and comments on each PR are quite interesting and it is great to hear that TLVC I/O runs quite a bit faster than ELKS as a result. I am interested to learn more about short-term vs long term speedups as well.

If you are interested, I have a number of questions and/or comments about the side-effects of a kernel that now may be reentered (not actually, but effectively through other tasks that might get awakened within a previously-wait-to-I/O-completed system call), as well as thoughts on how to fully eliminate all BIOS dependencies, which it sounds like could be a goal of TLVC.

I thought to open this issue for comments, as well as possibly comment or question on various open issues and commits, if you would like.

Thank you!

**Comment by Mellvik** [comment]
Hi @ghaerr, thanks for stopping by.

TLVC has indeed been an interesting journey so far, and some encouraging results. About speed - no benchmarks yet, and honestly I don't expect the big differences in terms of raw speed. Responsiveness however, is a different story. It's already vastly different from ELKS, and will improve more when the HD driver becomes fully interrupt driven and likewise for the serial driver  output.

My making the repository public this early was premature because there is still so much being changed almost from day to day. Github forced my hand by refusing to make the wiki available unless I opened the gates, and I really needed to start unloading some of the notes and docs written along the way.

The frequent changes and still rather infrequent PRs mean that commenting on code and specific bugs may not be very productive. With that caveat however, comments etc. are welcome. My intent is to have the base platform stable by the end of August. 

-M
